// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5_LXqLOyel9E8XCrhkQ3FDlOtkKymVBc',
    appId: '1:899474632153:web:41e13e46d6b5f481e93dc8',
    messagingSenderId: '899474632153',
    projectId: 'test-app-18faf',
    authDomain: 'test-app-18faf.firebaseapp.com',
    storageBucket: 'test-app-18faf.firebasestorage.app',
    measurementId: 'G-G3X4TXTYTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbtGhdHFsMvl-5czZOcAmmM_wBYcbewZs',
    appId: '1:899474632153:android:2f630519724607cce93dc8',
    messagingSenderId: '899474632153',
    projectId: 'test-app-18faf',
    storageBucket: 'test-app-18faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFmhnRMBLit2TBQDg1ODyydZwMdywVsAc',
    appId: '1:899474632153:ios:5231c3e36533d285e93dc8',
    messagingSenderId: '899474632153',
    projectId: 'test-app-18faf',
    storageBucket: 'test-app-18faf.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFmhnRMBLit2TBQDg1ODyydZwMdywVsAc',
    appId: '1:899474632153:ios:5231c3e36533d285e93dc8',
    messagingSenderId: '899474632153',
    projectId: 'test-app-18faf',
    storageBucket: 'test-app-18faf.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5_LXqLOyel9E8XCrhkQ3FDlOtkKymVBc',
    appId: '1:899474632153:web:01da641777852df7e93dc8',
    messagingSenderId: '899474632153',
    projectId: 'test-app-18faf',
    authDomain: 'test-app-18faf.firebaseapp.com',
    storageBucket: 'test-app-18faf.firebasestorage.app',
    measurementId: 'G-FZ4FH6EQ50',
  );
}
